platform :ios, '7.0'
target 'CBNMagazine' do
pod 'SDWebImage'
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'MMDrawerController'
pod 'DKNightVersion'
pod 'MJRefresh'
pod 'UMengSocial'
pod 'MJExtension'
pod 'YRJSONAdapter'
pod 'SSKeychain'
pod 'SFFocusViewLayout'
end